
#Deep Learning con Python



### Autor: Erwing FC 

#### ~erwingforerocastro@gmail.com 


In [0]:
#numpy
import numpy as np 
x = np.array(8) 
print ("x: ", x) 
print ("x ndim: ", x.ndim) #dimension 0D,1D,2D,3D,4D
print ("x shape:", x.shape) #tamaño vectorial
print ("x size: ", x.size)  #tamaño
print ("x dtype: ", x.dtype) #tipo de dato

#vector o tensor 1D
x = np.array([2.3 , 4.2 , 3.3, 1.8]) 
print ("x: ", x) 
print ("x ndim: ", x.ndim) 
print ("x shape:", x.shape) 
print ("x size: ", x.size) 
print ("x dtype: ", x.dtype)

#matriz o tensor 2D
x = np.array([[1,2,3], [4,5,6], [7,8,9]]) 
print ("x:\n", x) 
print ("x ndim: ", x.ndim) 
print ("x shape:", x.shape) 
print ("x size: ", x.size) 
print ("x dtype: ", x.dtype)

#tensor 3D
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) 
print ("x:\n", x) 
print ("x ndim: ", x.ndim)  
print ("x shape:", x.shape) 
print ("x size: ", x.size) 
print ("x dtype: ", x.dtype)

In [0]:
#creación rapida de tensores
print ("np.zeros((3,3)):\n", np.zeros((3,3))) #matriz 3x3 de ceros
print ("np.ones((3,3)):\n", np.ones((3,3)))   #matriz 3x3 de unos
print ("np.eye((3)): (identity matrix)\n", np.eye((3))) #matriz 3x3 identidad (ceros con diagonal unos)
print ("np.random.random((3,3)):\n", np.random.random((3,3))) #matriz 3x3 con numeros random


In [9]:
#Manipulación de tensores
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) 
print (x) 
print ("x columna 1: ", x[:, 1]) 
print ("x fila 0: ", x[0, :]) 
print ("x filas 0,1 & columnas 1,2: \n", x[0:2, 1:3]) #toma de 0,1 pero no el 2, igual con 1:3

print()
#multiplicar tensores
a = np.array([[1,2,3], [4,5,6]], dtype=np.int32) 
b = np.array([[7,8], [9,10], [11, 12]], dtype=np.int32) 
c = a.dot(b) 
print (f"{a.shape} · {b.shape} = {c.shape}") 
print (c) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x columna 1:  [ 2  6 10]
x fila 0:  [1 2 3 4]
x filas 0,1 & columnas 1,2: 
 [[2 3]
 [6 7]]

(2, 3) · (3, 2) = (2, 2)
[[ 58  64]
 [139 154]]


In [0]:
#transformación
x = np.array([[1,2,3,4,5,6]]) 
print (x) 
print ("x.shape: ", x.shape) 

y = np.reshape(x, (2, 3)) 
print ("y: \n", y) 
print ("y.shape: ", y.shape) 

z = np.reshape(x, (2, -1)) 
print ("z: \n", z) 
print ("z.shape: ", z.shape) 

In [0]:
#Borrar o añadir dimensiones a un tensor
x = np.array([[1,2,3],[4,5,6]]) 
print ("x:\n", x) 
print ("x.shape: ", x.shape) 

y = np.expand_dims(x, 1) #añadir una dimension
print ("y: \n", y) 
print ("y.shape: ", y.shape)

x = np.array([[[1,2,3]],[[4,5,6]]]) 
print ("x:\n", x) 
print ("x.shape: ", x.shape) 

y = np.squeeze(x, 1) # squitar una dimension
print ("y: \n", y) 
print ("y.shape: ", y.shape) 

In [0]:
#valor maximo de un tensor

x = np.array([1,2,3,4]) 
print (x) 
print (np.argmax(x)) #indice maximo 
print (np.max(x)) #valor maximo

print()
print("mismo valor toma el primer indice:")
#mismo valor toma el primer indice
x = np.array([1,2,4,4]) 
print (x) 
print (np.argmax(x)) 
print (np.max(x)) 

print()
print("2D:")
#2D
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) 
print (x) 
print (np.argmax(x)) 
print (np.max(x)) 

print()
print("Especificando el eje:")
#Especificando el eje
print (np.argmax(x, axis=0))  #axis=0 trae los indice de la fila con el indice mas alto
print (np.max(x, axis=0))     #trae los valores de la fila con el valor mas alto
print (np.argmax(x, axis=1))  #axis=1 igual pero con columna
print (np.max(x, axis=1))     